# Generated by Django 4.0.4 on 2022-04-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField(verbose_name='')),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
