# Generated by Django 4.0.4 on 2022-04-21 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_ethnos_alter_article_image_article_ethnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=255)),
                ('body', models.TextField(verbose_name='')),
                ('date', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.article')),
            ],
        ),
    ]
