# Generated by Django 4.0.4 on 2022-04-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethnos',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
